### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by trebmuh** [sonejostudios/SuperBeatRepeater#1]
@sonejostudios salut Vincent.

J'essaie d'empaqueter ce logiciel pour LibraZiK-2.

Si je le compile normalement dans un terminal avec `faust2jaqt -midi SuperBeatRepeater.dsp`, alors pas de soucis, l'exécutable binaire est construit.

Par contre, si j'essaie de le construire dans un chroot pour faire un paquet propre (avec l'outil pbuilder de Debian), alors j'ai cette erreur:

```
make[1]: Entering directory '/build/superbeatrepeater-1.1'
faust2jaqt -midi SuperBeatRepeater.dsp
ERROR : Unable to open file analyzers.lib
```

C'est franchement étrange et je ne comprends pas pourquoi ça fonctionne dans mon terminal mais pas dans un chroot pbuilder. Peut être ai-je une dépendance sur mon ordi qui fait que la compilation par terminal fonctionne, et que j'aurai oublié de mettre dans le chroot pbuilder ? Il vient d'où ce analyzers.lib?

**Comment by sonejostudios** [comment]
Salut Olinuxx!

ca, c'est une très bonne question, que je ne peux malheueusement pas répondre. Par contre, essaye de la posier sur la mailing list de faust: faudiostream-users@lists.sourceforge.net

Es-tu en train de créer des paquets .deb ? pour faust? C'est un truc que j'ai beaucoup essayé mais jamais réussi :( pourrais-tu me donner un coup de main là-dessus? ou encore mieux, ecrire un simple "how-to" quelque part? Ca serait vraiment génial!
a+

**Comment by trebmuh** [comment]
J'ai peut être une piste. Sur mon ordi sur lequel je compile dans un terminal, j'ai une version de faust en 2.14.4 d'installé. Par contre, dans le chroot pbuilder, j'ai la version de base de debian 0.9.95 . Penses-tu que ça puisse faire une différence ?

**Comment by trebmuh** [comment]
> Es-tu en train de créer des paquets .deb ?

Oui.

> pour faust?

Comment ça "pour faust" ? Il y a déjà des paquets présents dans Debian pour faust.

Là, je suis en train de créer des paquets deb pour LibraZiK-2 (base Debian Stretch) pour tes logiciels. Pour l'instant, j'ai des paquets en test pour : xymatrix, livefader, stereolevels, audiothrough16, mixer4x, panoramix, stereoswitch, abswitchstereo, midiclockclick, stereobalancemeter, stereoknot, livemixer, supercutsequencer, et delooper. J'ai pour l'instant juste des paquets construits et n'ai pas encore testé les logiciels.


> C'est un truc que j'ai beaucoup essayé mais jamais réussi :( pourrais-tu me donner un coup de main là-dessus? ou encore mieux, ecrire un simple "how-to" quelque part? Ca serait vraiment génial!

Ça n'existe pas un "simple how-to" pour construire des deb. Un bon point de départ, c'est le [guide du mainteneur Debian](https://www.debian.org/doc/manuals/maint-guide/).

Si tu m'en dis un peu plus (çàd: un peu plus précis sur ce que tu souhaiterais faire), peut être pourrai-je t'aider ou t'aiguiller.

**Comment by sonejostudios** [comment]
> Comment ça "pour faust" ? Il y a déjà des paquets présents dans Debian pour faust.

je veux dir des paquets .deb pas de faust mais pour des logiciels écrits avec faust. Apparemment, oui, et c'est génial!

Malheureusement je suis très occupé en ce moment et je peux pas me pencher là-dessus... je vais quand même jeter un coup d'oeil au guide du mainteneur Debian.

Est-ce qu'il y a un repository LibraZik et les paquets, sont-ils compatible avec Ubuntu/Linuxmint ?

**Comment by trebmuh** [comment]
En utilisant la version 2.14.4 de faust, je suis parvenu à faire un paquet. Problème résolu donc.

> je veux dir des paquets .deb pas de faust mais pour des logiciels écrits avec faust. Apparemment, oui, et c'est génial!

Oui, c'est ça, j'ai fait des paquets pour 16 logiciels en faust de chez toi, les 14 cités ci-dessus, plus drumseq et superbeatrepeater à présent que je suis parvenu à les empaqueter en utilisant la version 2.14.4 de faust.

> Est-ce qu'il y a un repository LibraZik

Oui il y a un dépôt LibraZiK-2.

> et les paquets, sont-ils compatible avec Ubuntu/Linuxmint ?

Je ne sais pas. Ils ont fabriqués à partir des sources de Debian et de LibraZiK-2. Ceci dit, tu peux essayer les paquets tels quels (avec un peu de chance, peut être que ça peut fonctionner comme ça), ou bien réutiliser les règles d'empaquetage de mes paquets pour reconstruire un paquet pour Ubuntu/Mint.

Dans tous les cas, je ferme ici car mon problème originel est résolu (merci pour l'aide), et tu peux passer me voir [sur le canal IRC de LibraZiK](https://librazik.tuxfamily.org/base-site-LZK/contact.php#IRC) pour venir discuter des paquets si tu le souhaites.

À bientôt,
Olivier
